//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Segplan.ReplicateCustomField.App.WebLoginReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/office/project/server/webservices/LoginWindows/", ConfigurationName="WebLoginReference.LoginWindowsSoap")]
    public interface LoginWindowsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/LoginWindows/Login" +
            "", ReplyAction="*")]
        bool Login();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/LoginWindows/Login" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> LoginAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/LoginWindows/Logof" +
            "f", ReplyAction="*")]
        void Logoff();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/LoginWindows/Logof" +
            "f", ReplyAction="*")]
        System.Threading.Tasks.Task LogoffAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginWindowsSoapChannel : Segplan.ReplicateCustomField.App.WebLoginReference.LoginWindowsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginWindowsSoapClient : System.ServiceModel.ClientBase<Segplan.ReplicateCustomField.App.WebLoginReference.LoginWindowsSoap>, Segplan.ReplicateCustomField.App.WebLoginReference.LoginWindowsSoap {
        
        public LoginWindowsSoapClient() {
        }
        
        public LoginWindowsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginWindowsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginWindowsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginWindowsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login() {
            return base.Channel.Login();
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync() {
            return base.Channel.LoginAsync();
        }
        
        public void Logoff() {
            base.Channel.Logoff();
        }
        
        public System.Threading.Tasks.Task LogoffAsync() {
            return base.Channel.LogoffAsync();
        }
    }
}
